# solenoid_test prj.conf

CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_SERIAL=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_GPIO=y
CONFIG_GPIO_INIT_PRIORITY=40

# main 栈给得宽裕一点，便于将来加按键中断 / shell
CONFIG_MAIN_STACK_SIZE=4096
